/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class singerstone_com_superapp_ndkinterface_NdkInterface */

#ifndef _Included_singerstone_com_superapp_ndkinterface_NdkInterface
#define _Included_singerstone_com_superapp_ndkinterface_NdkInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     singerstone_com_superapp_ndkinterface_NdkInterface
 * Method:    getServiceName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_singerstone_com_superapp_ndkinterface_NdkInterface_getServiceName(JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
