/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class singerstone_com_superapp_ndkinterface_NdkInterface */

#ifndef _Included_singerstone_com_superapp_ndkinterface_NdkInterface
#define _Included_singerstone_com_superapp_ndkinterface_NdkInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     singerstone_com_superapp_ndkinterface_NdkInterface
 * Method:    getServiceName
 * Signature: ()Ljava/lang/String;
 */

jstring GetServiceName(JNIEnv *, jclass);
jint RegisterNatives(JNIEnv *env);
jint JNI_OnLoad(JavaVM *vm, void *reserved);

/*
 * Class:     singerstone_com_superapp_ndkinterface_NdkInterface
 * Method:    genCrash
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_singerstone_com_superapp_ndkinterface_NdkInterface_genCrash
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_singerstone_com_superapp_ndkinterface_NdkInterface_genMallocOOM
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_singerstone_com_superapp_ndkinterface_NdkInterface_genMallocOOMVM
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_singerstone_com_superapp_ndkinterface_NdkInterface_genMmapOOM
  (JNIEnv *, jclass);



#ifdef __cplusplus
}
#endif
#endif
