/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class singerstone_com_superapp_ndkinterface_CrashLib */

#ifndef _Included_singerstone_com_superapp_ndkinterface_CrashLib
#define _Included_singerstone_com_superapp_ndkinterface_CrashLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     singerstone_com_superapp_ndkinterface_CrashLib
 * Method:    breakpadInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_singerstone_com_superapp_ndkinterface_CrashLib_breakpadInit
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
